spring:
  h2:
    console:
      enabled: true
      path: /check24
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:mem:check24;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: check24
    password: check2424
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
    defer-datasource-initialization: true

server:
  port: 8085

service:
  movie:
    exception:
      notFound: no such movie found!
  user:
    exception:
      notFound: no such user found!